name: Deploy to GitHub Pages

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo CLI
        run: npm install -g @expo/cli

      - name: Build for web
        run: npx expo export --platform web --output-dir docs
        env:
          NODE_ENV: production

      - name: Copy privacy policy to docs
        run: cp privacy-policy.html docs/

      - name: Copy documentation index
        run: cp docs-index.html docs/info.html

      - name: Fix paths for GitHub Pages
        run: |
          # Fix absolute paths in index.html to work with GitHub Pages subdirectory
          sed -i 's|href="/|href="/lo-siento/|g' docs/index.html
          sed -i 's|src="/_expo/|src="/lo-siento/_expo/|g' docs/index.html

      - name: Add .nojekyll file
        run: touch docs/.nojekyll

      - name: Commit and push to staging
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "Deploy to GitHub Pages" || exit 0
          git push
